# Generated by Django 5.0.4 on 2024-05-28 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_model',
            name='firstname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user_model',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
