# Generated by Django 4.2.11 on 2024-05-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=256)),
                ("summary", models.TextField()),
                ("date", models.DateField()),
                ("cloud", models.TextField(blank=True, null=True)),
                ("analysis", models.TextField(blank=True, null=True)),
                ("isscrape", models.BooleanField(default=False)),
            ],
        ),
    ]
